AllCops:

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Gemfile'
    - 'config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Guardfile'
    - 'Capfile'

  TargetRubyVersion: 2.4

Rails/Blank:
  Enabled: false # causes error

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 170

Style/Lambda:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
