require: rubocop-performance

AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Guardfile'
    - 'Capfile'
    - 'node_modules/**/*'

  TargetRubyVersion: 2.6

Style/ExpandPathArguments:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/RedundantReceiverInWithOptions:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Style/Lambda:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
