AllCops:

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Gemfile'
    - 'config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 170

Style/Lambda:
  Enabled: false
