
default: &default
  broker_address: "192.168.1.3"
  broker_username: "server"
  broker_password: "server"

development:
  <<: *default

test:
  <<: *default

production:
  broker_address: "server.slon-ds.ru"
  broker_username: "server"
  broker_password: "db6cd4e8eb4afff3443baf2381adc7b6"