---
:logfile: ./log/sidekiq.log
:concurrency: 3
:queues:
  - default
  - mailers
  - notifiers
  - files_processing

:schedule:
  timeouts:
    class: TimeoutsCheckJob
    every: '20s'

  tmp_uploads_cleanup:
    class: TmpUploadsCleanupJob
    cron: '5 0 * * *'
